#pragma once

#pragma comment(lib,"AppFrame.lib")

#include "dxLib.h"
#include "Application/ApplicationBase.h"
#include "CFile/CFile.h"
#include "mymath.h"

#include <string>
#include <vector>
#include <array>
#include <cmath>
#include <algorithm>
#include <functional>
#include <memory>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <stack>
#include <queue>
#include <list>
#include <sstream>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <cassert>
#include <cstdlib>
#include <ctime>
#include <cstdarg>
#include <thread>
#include <mutex>
#include <atomic>
#include <condition_variable>
#include <future>
#include <chrono>
#include <random>
#include <type_traits>
#include <utility>
#include <limits>
#include <tuple>
#include <variant>
#include <bitset>
#include <regex>
#include <locale>
#include <codecvt>
#include <cwctype>
#include <filesystem>
#include <streambuf>

