name: CI Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # ここで「Game」フォルダの中に移動して復元させる
    - name: Restore dependencies
      run: dotnet restore Game/Game.sln
      
    # ここも同じように指定する
    - name: Build
      run: dotnet build Game/Game.sln --configuration Release --no-restore